name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: artem-sytnyk/buildozer-action@v1
        with:
          command: buildozer android release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SaniaMalik-APK
          path: bin/*.apk
          if-no-files-found: error
